server:
  port: 8765
  undertow:
    threads:
      worker: 200
      io: 16
    buffer-size: 16384

spring:
  application:
    name: api-gateway
  
  cloud:
    gateway:
      # CORS Configuration
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true
            maxAge: 3600
      
      # Default Filters
      default-filters:
        - AddRequestHeader=X-Gateway-Timestamp, ${timestamp}
        - AddRequestHeader=X-Gateway-Version, 2.0.0
        - RemoveRequestHeader=Cookie
        
      # Discovery Configuration
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
          
      # Routes Configuration
      routes:
        # User Service Routes
        - id: user-service-auth
          uri: lb://user-service
          predicates:
            - Path=/api/v1/auth/**
          filters:
            - StripPrefix=0
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 10
                redis-rate-limiter.burstCapacity: 20
                
        - id: user-service-users
          uri: lb://user-service
          predicates:
            - Path=/api/v1/users/**
          filters:
            - StripPrefix=0
            - AuthenticationFilter
            
        # Driver Service Routes  
        - id: driver-service-auth
          uri: lb://driver-service
          predicates:
            - Path=/api/v1/drivers/auth/**
          filters:
            - StripPrefix=0
            
        - id: driver-service-drivers
          uri: lb://driver-service
          predicates:
            - Path=/api/v1/drivers/**
          filters:
            - StripPrefix=0
            - AuthenticationFilter
            
        # Ride Service Routes
        - id: ride-service-rides
          uri: lb://ride-service
          predicates:
            - Path=/api/v1/rides/**
          filters:
            - StripPrefix=0
            - AuthenticationFilter
            
        - id: ride-service-matching
          uri: lb://ride-service
          predicates:
            - Path=/api/v1/matching/**
          filters:
            - StripPrefix=0
            - AuthenticationFilter
            
        # Payment Hub Service Routes
        - id: payment-service-payments
          uri: lb://payment-hub-service
          predicates:
            - Path=/api/v1/payments/**
          filters:
            - StripPrefix=0
            - AuthenticationFilter
            
        # Emergency Service Routes
        - id: emergency-service
          uri: lb://emergency-service
          predicates:
            - Path=/api/v1/emergency/**
          filters:
            - StripPrefix=0
            - AuthenticationFilter
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 20
                redis-rate-limiter.burstCapacity: 40
                
        # Travel Integration Service Routes
        - id: travel-integration-service
          uri: lb://travel-integration-service
          predicates:
            - Path=/api/v1/travel/**
          filters:
            - StripPrefix=0
            - AuthenticationFilter
            
        # WolKurye Service Routes
        - id: wolkurye-service
          uri: lb://wolkurye-service
          predicates:
            - Path=/api/v1/kurye/**
          filters:
            - StripPrefix=0
            - AuthenticationFilter
            
        # AI/ML Service Routes
        - id: ai-ml-service
          uri: lb://ai-ml-service
          predicates:
            - Path=/api/v1/ai/**
          filters:
            - StripPrefix=0
            - AuthenticationFilter
            - name: RequestSize
              args:
                maxSize: 50MB
                
        # Smart Vehicle Service Routes
        - id: smart-vehicle-service
          uri: lb://smart-vehicle-service
          predicates:
            - Path=/api/v1/smart-vehicles/**
          filters:
            - StripPrefix=0
            - AuthenticationFilter
            
        # Analytics Service Routes
        - id: analytics-service
          uri: lb://analytics-service
          predicates:
            - Path=/api/v1/analytics/**
          filters:
            - StripPrefix=0
            - AuthenticationFilter
            
        # Global Performance Service Routes
        - id: global-performance-service
          uri: lb://global-performance-service
          predicates:
            - Path=/api/v1/performance/**
          filters:
            - StripPrefix=0
            - AuthenticationFilter
            
        # Marketing Service Routes
        - id: marketing-service
          uri: lb://marketing-service
          predicates:
            - Path=/api/v1/marketing/**
          filters:
            - StripPrefix=0
            - AuthenticationFilter
            
        # Subscription Service Routes
        - id: subscription-service
          uri: lb://subscription-service
          predicates:
            - Path=/api/v1/subscriptions/**
          filters:
            - StripPrefix=0
            - AuthenticationFilter
          
  # Redis Configuration for Rate Limiting
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:woltaxi_redis_2024}
      database: 0
      timeout: 2000ms
      lettuce:
        pool:
          max-active: 10
          max-idle: 5
          min-idle: 1

# Eureka Configuration
eureka:
  client:
    service-url:
      defaultZone: http://woltaxi-admin:woltaxi-2024-secure@${EUREKA_HOST:localhost}:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
    
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    metadata-map:
      version: "2.0.0"
      service-type: "api-gateway"
      cluster: "woltaxi-main"

# Management Endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,gateway,refresh
  endpoint:
    health:
      show-details: always
    gateway:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true

# Circuit Breaker Configuration
resilience4j:
  circuitbreaker:
    instances:
      user-service-cb:
        failure-rate-threshold: 50
        wait-duration-in-open-state: 30s
        sliding-window-size: 10
        minimum-number-of-calls: 5
      ride-service-cb:
        failure-rate-threshold: 50
        wait-duration-in-open-state: 30s
        sliding-window-size: 10
        minimum-number-of-calls: 5
      driver-service-cb:
        failure-rate-threshold: 50
        wait-duration-in-open-state: 30s
        sliding-window-size: 10
        minimum-number-of-calls: 5

# Logging Configuration
logging:
  level:
    org.springframework.cloud.gateway: INFO
    org.springframework.security: INFO
    com.woltaxi.gateway: DEBUG
    reactor.netty.http.client: INFO
    root: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{50} - %msg%n"

# WOLTAXI Gateway Configuration
woltaxi:
  gateway:
    version: "2.0.0"
    
    # Rate Limiting
    rate-limit:
      enabled: true
      requests-per-second: 100
      burst-capacity: 200
      replenish-rate: 50
      
    # Security
    security:
      jwt-secret: ${JWT_SECRET:woltaxi-gateway-secret-2024-enterprise}
      cors-enabled: true
      csrf-disabled: true
      
    # Timeout Configuration
    timeout:
      connect: 5000
      response: 30000
      
    # Retry Configuration
    retry:
      max-attempts: 3
      backoff-delay: 1000
      
    # Health Check
    health:
      check-interval: 30
      timeout: 10
      
    # Monitoring
    monitoring:
      enabled: true
      metrics-export: true
      logging-enabled: true