# 🔒 WOLTAXI IP Protection Service Configuration

server:
  port: 8090
  servlet:
    context-path: /api/v1/ip-protection

spring:
  application:
    name: ip-protection-service
  
  # Database Configuration
  datasource:
    url: jdbc:h2:mem:ipprotection
    driver-class-name: org.h2.Driver
    username: admin
    password: woltaxi2025
    
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        
  h2:
    console:
      enabled: true
      path: /h2-console
      
  # Cache Configuration
  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=1000,expireAfterWrite=300s

# Eureka Client Configuration
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30

# Management and Monitoring
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,licenses,watermarks
  endpoint:
    health:
      show-details: always
  metrics:
    export:
      prometheus:
        enabled: true

# IP Protection Specific Configuration
ip-protection:
  license:
    validation-enabled: true
    strict-mode: false
    max-grace-period-days: 7
    encryption:
      algorithm: AES-256-GCM
      key-size: 256
    jwt:
      secret: woltaxi-ip-protection-super-secret-key-2025
      expiration: 86400000 # 24 hours
      
  watermark:
    default-strength: 7
    supported-formats: [PNG, JPG, PDF, MP4, AVI]
    steganography:
      enabled: true
      algorithm: LSB
      
  security:
    obfuscation:
      enabled: true
      level: AGGRESSIVE
    anti-tampering:
      enabled: true
      checksum-validation: true
    reverse-engineering:
      detection: true
      block-debuggers: true
      
  usage-tracking:
    enabled: true
    retention-days: 365
    analytics:
      real-time: true
      batch-processing: false
      
  legal:
    compliance-monitoring: true
    audit-logging: true
    gdpr-compliant: true
    terms-validation: true

# Logging Configuration
logging:
  level:
    com.woltaxi.ipprotection: INFO
    org.springframework.security: WARN
    org.hibernate: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/ip-protection-service.log