server:
  port: 8082

spring:
  application:
    name: ride-service
    
  datasource:
    url: jdbc:postgresql://localhost:5432/woltaxi_rides
    username: ${DB_USERNAME:woltaxi_user}
    password: ${DB_PASSWORD:woltaxi_2024}
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

eureka:
  client:
    service-url:
      defaultZone: http://woltaxi-admin:woltaxi-2024-secure@localhost:8761/eureka/
    
woltaxi:
  ride:
    matching:
      radius-km: 5.0
      max-wait-time: 300
      priority-factors:
        - distance
        - driver-rating
        - vehicle-type
        - user-preference
    
    pricing:
      base-fare: 15.0
      per-km: 8.0
      per-minute: 3.0
      minimum-fare: 40.0
      surge-multiplier-max: 3.0
